# 1. Stage: Build Environment
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Ensure the custom webpack builder is installed
RUN npm install --save-dev @angular-builders/custom-webpack

RUN npm run build --prod

# 2. Stage: Production Environment
FROM nginx:alpine

COPY --from=build /app/dist/programmierprojekt /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
